<a href="https://colab.research.google.com/github/Pubudu-98/Colab/blob/main/Data_Science_Project_EV_Data_Analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Testing Colab CPU & GPU*

In [7]:
import torch
import time

def compute(device):

    x = torch.rand(10000, 10000, device=device)

    start = time.time()

    y = x @ x

    torch.cuda.synchronize() if device == 'cuda' else None
    end = time.time()
    print(end-start)

In [8]:
compute('cpu') # CPU performence

27.032788515090942

In [9]:
compute('cuda') # GPU performence

0.538245439529419

## **Data Science Life Cycle**


*   Business reqiurement
*   Data aquisition


*   Data processing
*   Data exploration


*   Data modeling
*   Deployment

**Import Libraries**

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
data = pd.read_csv('/content/Electric_Vehicle_Data.csv')

### **Load Data and Initial Inspection**

In [ ]:
data = pd.read_csv('/content/Electric_Vehicle_Data.csv')
display(data.head())

In [12]:
data.head(5)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJYGDEE1L,King,Seattle,WA,98122,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291,0,37,125701579,POINT (-122.30839 47.610365),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
1,7SAYGDEE9P,Snohomish,Bothell,WA,98021,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,1,244285107,POINT (-122.179458 47.802589),PUGET SOUND ENERGY INC,5.306105e+10
2,5YJSA1E4XK,King,Seattle,WA,98109,2019,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270,0,36,156773144,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5YJSA1E27G,King,Issaquah,WA,98027,2016,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,5,165103011,POINT (-122.03646 47.534065),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,5YJYGDEE5M,Kitsap,Suquamish,WA,98392,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,23,205138552,POINT (-122.55717 47.733415),PUGET SOUND ENERGY INC,5.303594e+10

In [13]:
data.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', '2020 Census Tract'],
      dtype='object')

In [14]:
data.tail()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
26135,ZACPDFCW4R,King,Tukwila,WA,98188,2024,DODGE,HORNET,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32,0,11,262235977,POINT (-122.29179 47.43473),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
26136,7SAXCAE55P,King,Redmond,WA,98052,2023,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,45,259925109,POINT (-122.12302 47.67668),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
26137,KNDAFFS53R,Snohomish,Bothell,WA,98012,2024,KIA,EV9,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,1,260807375,POINT (-122.1873 47.820245),PUGET SOUND ENERGY INC,5.306105e+10
26138,5YJSA1E28H,Clark,La Center,WA,98629,2017,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,18,349585155,POINT (-122.6706246 45.8662548),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
26139,7SAXCBE53P,King,Redmond,WA,98052,2023,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,45,249776502,POINT (,NaN,NaN

In [16]:
data.isnull().sum()

VIN (1-10)                                           0
County                                               0
City                                                 0
State                                                0
Postal Code                                          0
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       0
Base MSRP                                            0
Legislative District                                 0
DOL Vehicle ID                                       0
Vehicle Location                                     0
Electric Utility                                     1
2020 Census Tract                                    1
dtype: int64

In [17]:
data.describe()

,Postal Code,Model Year,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,2020 Census Tract
count,26140.000000,26140.000000,26140.000000,26140.000000,26140.000000,2.614000e+04,2.613900e+04
mean,98177.277085,2020.575937,59.707842,1096.925784,32.588715,2.209603e+08,5.303341e+10
std,216.098706,2.946715,92.379858,8341.829701,14.617787,7.672124e+07,1.178244e+07
min,98001.000000,2000.000000,0.000000,0.000000,1.000000,2.770200e+04,5.300796e+10
25%,98033.000000,2019.000000,0.000000,0.000000,20.000000,1.827179e+08,5.303301e+10
50%,98107.000000,2022.000000,0.000000,0.000000,37.000000,2.284266e+08,5.303302e+10
75%,98188.000000,2023.000000,83.000000,0.000000,45.000000,2.546799e+08,5.303303e+10
max,99362.000000,2024.000000,337.000000,184400.000000,49.000000,4.789259e+08,5.307794e+10

### **Data Types and Non-Null Values**

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26140 entries, 0 to 26139
Data columns (total 17 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   VIN (1-10)                                         26140 non-null  object
 1   County                                             26140 non-null  object
 2   City                                               26140 non-null  object
 3   State                                              26140 non-null  object
 4   Postal Code                                        26140 non-null  int64
 5   Model Year                                         26140 non-null  int64
 6   Make                                               26140 non-null  object
 7   Model                                              26140 non-null  object
 8   Electric Vehicle Type                              26140 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  26140 non-null  object
 10  Electric Range                                     26140 non-null  int64
 11  Base MSRP                                          26140 non-null  int64
 12  Legislative District                               26140 non-null  int64
 13  DOL Vehicle ID                                     26140 non-null  int64
 14  Vehicle Location                                   26140 non-null  object
 15  Electric Utility                                   26139 non-null  object
 16  2020 Census Tract                                  26139 non-null  float64
dtypes: float64(1), int64(6), object(10)
memory usage: 3.4+ MB