<a href="https://colab.research.google.com/github/Pubudu-98/Colab/blob/main/Data_Science_Project_EV_Data_Analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Testing Colab CPU & GPU*

In [ ]:
import torch
import time

def compute(device):

    x = torch.rand(10000, 10000, device=device)

    start = time.time()

    y = x @ x

    torch.cuda.synchronize() if device == 'cuda' else None
    end = time.time()
    print(end-start)

In [ ]:
compute('cpu') # CPU performence

19.78734254837036

In [ ]:
compute('cuda') # GPU performence

0.549095869064331

## **Data Science Life Cycle**


*   Business reqiurement
*   Data aquisition


*   Data processing
*   Data exploration


*   Data modeling
*   Deployment

**Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data = pd.read_csv('/content/Electric_Vehicle_Data.csv')

In [5]:
data.head(5)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJYGDEE1L,King,Seattle,WA,98122,2020.0,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,0.0,37.0,125701579.0,POINT (-122.30839 47.610365),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
1,7SAYGDEE9P,Snohomish,Bothell,WA,98021,2023.0,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,1.0,244285107.0,POINT (-122.179458 47.802589),PUGET SOUND ENERGY INC,5.306105e+10
2,5YJSA1E4XK,King,Seattle,WA,98109,2019.0,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,270.0,0.0,36.0,156773144.0,POINT (-122.34848 47.632405),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5YJSA1E27G,King,Issaquah,WA,98027,2016.0,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210.0,0.0,5.0,165103011.0,POINT (-122.03646 47.534065),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,5YJYGDEE5M,Kitsap,Suquamish,WA,98392,2021.0,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,23.0,205138552.0,POINT (-122.55717 47.733415),PUGET SOUND ENERGY INC,5.303594e+10

In [7]:
data.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Base MSRP', 'Legislative District', 'DOL Vehicle ID',
       'Vehicle Location', 'Electric Utility', '2020 Census Tract'],
      dtype='object')

In [9]:
data.tail()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
43528,7PDSGABL1P,Clark,Vancouver,WA,98683,2023.0,RIVIAN,R1S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,18.0,257501282.0,POINT (-122.4853873 45.6083347),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...,5.301104e+10
43529,KM8KRDAF8P,King,Redmond,WA,98052,2023.0,HYUNDAI,IONIQ 5,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,48.0,230941770.0,POINT (-122.12302 47.67668),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
43530,7SAYGDEE7P,King,Covington,WA,98042,2023.0,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,47.0,244682287.0,POINT (-122.111625 47.36078),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
43531,5YJ3E1EA9J,Kitsap,Kingston,WA,98346,2018.0,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,0.0,23.0,257720396.0,POINT (-122.50156 47.8019),PUGET SOUND ENERGY INC,5.303509e+10
43532,5YJYGDEF4L,King,Bellevue,WA,980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data.describe()

,Postal Code,Model Year,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,2020 Census Tract
count,43533.000000,43532.000000,43532.000000,43532.000000,43532.000000,4.353200e+04,4.353200e+04
mean,98173.833896,2020.629950,58.785537,1062.266723,31.914752,2.212242e+08,5.303348e+10
std,510.909988,2.925475,91.889849,8154.096642,14.611084,7.571696e+07,1.169989e+07
min,980.000000,2000.000000,0.000000,0.000000,1.000000,2.770200e+04,5.300796e+10
25%,98034.000000,2019.000000,0.000000,0.000000,18.000000,1.833491e+08,5.303301e+10
50%,98109.000000,2022.000000,0.000000,0.000000,36.000000,2.287518e+08,5.303302e+10
75%,98188.000000,2023.000000,81.000000,0.000000,45.000000,2.546447e+08,5.303303e+10
max,99362.000000,2024.000000,337.000000,184400.000000,49.000000,4.789259e+08,5.307794e+10

In [12]:
data.isnull().sum()

VIN (1-10)                                           0
County                                               0
City                                                 0
State                                                0
Postal Code                                          0
Model Year                                           1
Make                                                 1
Model                                                1
Electric Vehicle Type                                1
Clean Alternative Fuel Vehicle (CAFV) Eligibility    1
Electric Range                                       1
Base MSRP                                            1
Legislative District                                 1
DOL Vehicle ID                                       1
Vehicle Location                                     1
Electric Utility                                     1
2020 Census Tract                                    1
dtype: int64